apiVersion: v2
name: seafile
type: application
version: 0.1.3
appVersion: 13.0.17
icon: https://www.seafile.com/media/img/seafile-logo.png
home: https://github.com/gera-corp/helm-seafile
description: Seafile Server, Reliable and Performant File Sync and Share Solution on Kubernetes
keywords:
  - cloud
  - file
  - share
  - sync
sources:
  - https://github.com/gera-corp/helm-seafile
maintainers:
  - name: "gera"
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/changes: |
    - Update to Seafile 13.0.8
  artifacthub.io/images: |
    - name: Seafile
      image: docker.io/seafileltd/seafile-mc:13.0.8
  artifacthub.io/maintainers: |
    - name: gera
      email: exandore@gmail.com
dependencies:
  - name: mariadb
    version: 19.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: memcached
    version: 7.6.5
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 21.2.13
    condition: redis.enabled
