name: Publish Helm Chart to GHCR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  helm-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.14.0'

      - name: Login to GitHub Container Registry
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: echo "$GHCR_TOKEN" | helm registry login ghcr.io -u gera-corp --password-stdin


      - name: Package Helm Chart
        run: |
          mkdir -p packaged
          helm package . --destination packaged

      - name: Push Helm Chart to GHCR
        run: |
          for chart in packaged/*.tgz; do
            helm push $chart oci://ghcr.io/${{ github.repository_owner }}/helm-charts
          done
